kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: spark
  name: spark-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
