apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: my-notebook-pvc  
  namespace: spark  
spec:  
  accessModes:  
  - ReadWriteOnce  
  storageClassName: managed-premium  
  resources:  
    requests:  
      storage: 30Gi
