apiVersion: v1  
kind: Service  
metadata:  
  namespace: spark  
  name: my-notebook-deployment  
spec:  
  type: LoadBalancer  
  selector:  
    app: my-notebook  
  ports:  
    - protocol: TCP  
      port: 8888  
      targetPort: 8888  
---  
apiVersion: v1  
kind: Service  
metadata:  
  namespace: spark  
  name: spark-driver  
spec:  
  selector:  
    app: my-notebook  
  ports:  
    - protocol: TCP  
      port: 29413  
  clusterIP: None
