apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "sparkapp-test-{{ ts_nodash|lower }}-{{ task_instance.try_number }}  #custom
  namespace: "default"

spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "spark-py:1.0.0" #custom
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/airflow/dags/repo/dags/main.py  #custom
  sparkVersion: "3.1.2"
  restartPolicy:
    #type: Never
    type: OnFailure
    onFailureRetries: 0
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 0
    onSubmissionFailureRetryInterval: 20
  timeToLiveSeconds: 3600 # 1시간 있다가 sparkapplication 사라지는 설정
  driver:
    cores: 1
    coreLimit: "50m"
    memory: "512m"
    labels:
      version: 3.1.2
    serviceAccount: sparkoperator-spark-operator # sa
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: 3.1.2
